sudo: false
language: node_js

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

matrix:
  include:
    - os: linux
      node_js: "7"
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: linux
      node_js: "6"
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: linux
      node_js: "4.3"
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: osx
      node_js: "7"
      env: NO_WATCH_TESTS=1 JOB_PART=test
  allow_failures:
    - os: osx
  fast_finish: true

script: npm run travis:$JOB_PART
<<<<<<< HEAD
script: npm run test
script: npm run codecov

after_success:
  - echo 'xbr-after-success ~_~'
=======
script: npm run build

after_success:
  - echo 'test and build success ~_~'
>>>>>>> master

notifications:
  slack:
    rooms:
      - enjoy-coding-team:8PUCn7lnInAnVS4IbYekutNy#general
<<<<<<< HEAD
      - enjoy-coding-team:8PUCn7lnInAnVS4IbYekutNy#random
=======
      - enjoy-coding-team:8PUCn7lnInAnVS4IbYekutNy#random
>>>>>>> master
