sudo: false
language: node_js

branches:
  only:
    - master
    - develop
    - dev

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

matrix:
  include:
    - os: linux
      node_js: "7"
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: linux
      node_js: "6"
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: linux
      node_js: "4.3"
      env: NO_WATCH_TESTS=1 JOB_PART=test
    - os: osx
      node_js: "7"
      env: NO_WATCH_TESTS=1 JOB_PART=test
  allow_failures:
    - os: osx
  fast_finish: true

script: npm run travis:$JOB_PART

after_success:
  - echo 'xbr-after-success ~_~'